default_platform(:android)

platform :android do
  desc "Build and Upload to Firebase App Distribution"
  lane :firebase_distribution do
    sh "cd ../.. && flutter clean"
    sh "cd ../.. && flutter pub get"
    sh "cd ../.. && flutter build apk --release --flavor production -t lib/main_prod.dart"
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      release_notes: "What's new:\n#{last_git_commit[:message]}",
      groups: "CodeForgeTesters,ZimiruTesters",
    )
  end
end
