name: wasel_workspace

packages:
  - apps/*
  - packages/*

scripts:
  l10n:
    description: "Regenerate localizations in every package that has an l10n.yaml."
    run: flutter gen-l10n
    exec:
      concurrency: 1
    packageFilters:
      fileExists: l10n.yaml

  gen:
    description: "Run build_runner codegen in every package that depends on build_runner."
    run: dart run build_runner build
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: build_runner

  shorebird:release:dev:
    run: shorebird release android --flavor development
    exec:
      dir-exists: [android]
    description: "create a shorebird release for android (Development)"

  shorebird:release:prod:
    run: shorebird release android --flavor production
    exec:
      dir-exists: [android]
    description: 'create a shorebird release for android (Production)'

  
  shorebird:patch:dev:
    run: shorebird patch android --flavor development
    exec:
      dir-exists: [android]
    description: "Create a shorebird patch for android (Development)"

  shorebird:patch:prod:
    run: shorebird patch android --flavor production
    exec:
      dir-exists: [android]
    description: "Create a shorebird patch for android (Production)"
    
sdkPath: .fvm/flutter_sdk
